"""1

Revision ID: 03384b6fea4d
Revises: 
Create Date: 2023-11-06 23:05:54.881704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03384b6fea4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'photo_id')
    op.drop_column('examination', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('examination', sa.Column('adress', sa.VARCHAR(length=75), autoincrement=False, nullable=False))
    op.add_column('analysis', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
