"""2

Revision ID: 1aa56aa3a692
Revises: 03384b6fea4d
Create Date: 2023-11-06 23:08:27.719692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa56aa3a692'
down_revision: Union[str, None] = '03384b6fea4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('med_data', 'height',)
    op.drop_column('med_data', 'weight',)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
