"""3

Revision ID: c48ace6917c7
Revises: 1aa56aa3a692
Create Date: 2023-11-06 23:18:14.394899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48ace6917c7'
down_revision: Union[str, None] = '1aa56aa3a692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('med_data', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('med_data', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('med_data', 'weight')
    op.drop_column('med_data', 'height')
    # ### end Alembic commands ###
