"""2

Revision ID: e049c2d0dc1a
Revises: 86a958ebbc8f
Create Date: 2023-10-28 20:50:28.802683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e049c2d0dc1a'
down_revision: Union[str, None] = '86a958ebbc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('employee', sa.Column('first_name', sa.String(length=75), nullable=False))
    op.add_column('employee', sa.Column('last_name', sa.String(length=75), nullable=False))
    op.add_column('employee', sa.Column('middle_name', sa.String(length=75), nullable=False))
    op.add_column('employee', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('employee', sa.Column('email', sa.String(length=320), nullable=False))
    op.drop_constraint('employee_username_key', 'employee', type_='unique')
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.drop_column('employee', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.create_unique_constraint('employee_username_key', 'employee', ['username'])
    op.drop_column('employee', 'email')
    op.drop_column('employee', 'phone')
    op.drop_column('employee', 'middle_name')
    op.drop_column('employee', 'last_name')
    op.drop_column('employee', 'first_name')
    op.drop_table('post')
    # ### end Alembic commands ###
