"""4

Revision ID: e9a04f35b4f9
Revises: 4c82c01c2fd2
Create Date: 2023-11-12 19:39:22.774713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a04f35b4f9'
down_revision: Union[str, None] = '4c82c01c2fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_region_id_fkey', 'patient', type_='foreignkey')
    op.drop_column('patient', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patient_region_id_fkey', 'patient', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###
